/*
 * generated by Xtext
 */
package php.ware.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.antlr.AbstractAntlrTokenToAttributeIdMapper;

import php.ware.ui.syntaxcoloring.EntityAntlrTokenToAttributeIdMapper;
import php.ware.ui.syntaxcoloring.EntityHighlightingConfiguration;
import php.ware.ui.syntaxcoloring.SemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntityUiModule extends php.ware.ui.AbstractEntityUiModule {
	public EntityUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	/**
	 * Token to Attribute maps for Lexical Highlight
	 */
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAntlrTokenToAttributeIdMapper() {
		return EntityAntlrTokenToAttributeIdMapper.class;
	}

	/**
	 * Configuration for Lexical/Semantic Highlight
	 */
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return EntityHighlightingConfiguration.class;
	}

	/**
	 * Calculator for Semantic Highlight
	 */
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return SemanticHighlightingCalculator.class;
	}

}
