/*
 * generated by Xtext
 */
package php.ware.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntityUiModule extends php.ware.ui.AbstractEntityUiModule {
	public EntityUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
