/*
 * generated by Xtext
 */
package php.ware.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class EntityDescriptionLabelProvider extends
        DefaultDescriptionLabelProvider {

    // Labels and icons can be computed like this:

    @Override
    public String text(IEObjectDescription ele) {
        return ele.getName();
    }

    @Override
    public String image(IEObjectDescription ele) {
        return ele.getEClass().getName() + ".gif";
    }

}
